server:
  port: 8001

# ===========applicationName + druid-mysql8 driver==================
spring:
  application:
    name: cloud-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/db2024?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # Nacos 的地址
    sentinel:
      transport:
        dashboard: localhost:8858 # Sentinel控制台地址
        port: 8719 # 默认8719，假如被占用会自动从8719+1依次扫描
      web-context-unify: false


# ==========================mybatis==========================
mybatis:
  type-aliases-package: com.atguigu.cloud.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl